# pubspec.yaml
name: dappr
description: A new Flutter project.
publish_to: 'none' # Remove this line if you intend to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Ensure your Flutter SDK version is compatible

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  logger: ^2.0.2
  lottie: ^3.1.0
  audioplayers: ^6.0.0
  shared_preferences: ^2.2.3
  provider: ^6.0.5
  flutter_local_notifications: ^17.1.2
  url_launcher: ^6.2.6
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/dappr_logo_wrapped.json
    # --- Existing Assets ---
    - assets/images/nasi_goreng.jpg
    - assets/images/Mee_goreng _mamak.jpg # Ensure this filename with space is exactly as in your file system
    - assets/images/roti_jala.jpg
    - assets/images/spaghetti_aglio_olio.jpg
    - assets/images/tomyam_thai.jpg
    - assets/images/ayam_masak_merah.jpg
    - assets/images/ikan_bakar.jpg
    - assets/images/sambal_udang_simple.jpg
    - assets/images/sup_ayam_simple.jpg
    - assets/images/cooking_app_display_stockcake.jpg
    - assets/sounds/timer_alarm.mp3
    # --- Newly Added Assets ---
    - assets/images/laksa.jpg
    - assets/images/ayam_goreng.jpg
    - assets/images/kuih_lapis.jpg
    - assets/images/teh_tarik.jpg
    - assets/images/carrot_susu.jpg
    - assets/images/sup_ikan.jpg
    - assets/images/nasi_lemak.jpg


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat-Italic-VariableFont_wght.ttf
          style: italic
