# pubspec.yaml
name: dappr
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  logger: ^2.0.2
  lottie: ^2.0.0
  audioplayers: ^6.0.0 # Make sure this is still here and correctly indented
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/dappr_logo_wrapped.json
    - assets/images/nasi_goreng.jpg
    - assets/images/Mee_goreng _mamak.jpg # Ensure this filename with space is exactly as in your file system
    - assets/images/roti_jala.jpg
    - assets/images/spaghetti_aglio_olio.jpg
    - assets/images/tomyam_thai.jpg
    - assets/images/ayam_masak_merah.jpg
    - assets/images/ikan_bakar.jpg
    - assets/images/sambal_udang_simple.jpg
    - assets/images/sup_ayam_simple.jpg
    - assets/images/cooking_app_display_stockcake.jpg
    - assets/sounds/timer_alarm.mp3
    - assets/images/laksa.jpg
    - assets/images/ayam_goreng.jpg
    - assets/images/kuih_lapis.jpg
    - assets/images/teh_tarik.jpg
    - assets/images/carrot_susu.jpg
    - assets/images/sup_ikan.jpg
    - assets/images/nasi_lemak.jpg

  fonts:
    - family: Montserrat # This is the name you'll use in your code
      fonts:
        # Declare all the static fonts you want to use
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-VariableFont_wght.ttf # <--- Corrected path for variable font
        - asset: assets/fonts/Montserrat/Montserrat-Italic-VariableFont_wght.ttf # <--- Corrected path for italic variable font
          style: italic # Specify style for italic variable font
