# pubspec.yaml
name: dappr
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  logger: ^2.0.2
  lottie: ^2.0.0
  audioplayers: ^6.0.0 # Make sure this is still here and correctly indented

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/dappr_logo_wrapped.json
    # ... (ensure ALL your other images and sounds are listed here with correct paths)
    - assets/images/nasi_goreng.jpg
    - assets/images/Mee_goreng _mamak.jpg # Ensure this name matches disk exactly
    - assets/images/roti_jala.jpg
    - assets/images/spaghetti_aglio_olio.jpg
    - assets/images/tomyam_thai.jpg
    - assets/images/ayam_masak_merah.jpg
    - assets/images/ikan_bakar.jpg
    - assets/images/sambal_udang_simple.jpg
    - assets/images/sup_ayam_simple.jpg
    - assets/images/cooking_app_display_stockcake.jpg
    - assets/sounds/timer_alarm.mp3 # Make sure this is present and correct

  fonts: # This 'fonts:' must be directly under 'flutter:' (2 spaces indentation)
    - family: Montserrat # This '- family:' must be directly under 'fonts:' (4 spaces indentation)
      fonts: # This 'fonts:' must be directly under '- family:' (6 spaces indentation)
        - asset: assets/fonts/Montserrat-Regular.ttf # This '- asset:' must be directly under 'fonts:' (8 spaces indentation)
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf # As per your screenshot
        - asset: assets/fonts/Montserrat-Italic-VariableFont_wght.ttf # As per your screenshot
          style: italic
        - asset: assets/fonts/Montserrat-Black.ttf # Add this if you use it and it's missing
        - asset: assets/fonts/Montserrat-BlackItalic.ttf # Add this if you use it and it's missing
          style: italic
        - asset: assets/fonts/Montserrat-BoldItalic.ttf # Add this if you use it and it's missing
          style: italic
        - asset: assets/fonts/Montserrat-ExtraBold.ttf # Add this if you use it and it's missing
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf # Add this if you use it and it's missing
          style: italic
        - asset: assets/fonts/Montserrat-ExtraLight.ttf # Add this if you use it and it's missing
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf # Add this if you use it and it's missing
          style: italic
        - asset: assets/fonts/Montserrat-Italic.ttf # Add this if you use it and it's missing
          style: italic
        - asset: assets/fonts/Montserrat-LightItalic.ttf # Add this if you use it and it's missing
          style: italic
        - asset: assets/fonts/Montserrat-MediumItalic.ttf # Add this if you use it and it's missing
          style: italic
        - asset: assets/fonts/Montserrat-SemiBold.ttf # Add this if you use it and it's missing
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf # Add this if you use it and it's missing
          style: italic
        - asset: assets/fonts/Montserrat-Thin.ttf # Add this if you use it and it's missing
        - asset: assets/fonts/Montserrat-ThinItalic.ttf # Add this if you use it and it's missing
          style: italic